// import "jquery"
// import "proj4"
import "proj4leaflet"
import "leaflet"
import "leaflet-tilelayer-here"
import "leaflet-svgicon"
import "leaflet.markercluster"
import "src/decidim/homepage_interactive_map/interactive_map"
import "src/decidim/homepage_interactive_map/scope"
